// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/124-Aaron-Liu/gin-template/internal/app/api"
	"github.com/124-Aaron-Liu/gin-template/internal/app/api/handler"
	"github.com/124-Aaron-Liu/gin-template/internal/app/api/handler/user"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewApplication() (Application, error) {
	logger, err := newLogger()
	if err != nil {
		return Application{}, err
	}
	sugaredLogger := newSugaredLogger(logger)
	userHandler := user.NewHandler(sugaredLogger)
	handlerHandler := handler.NewHandler(sugaredLogger, userHandler)
	v := api.RouterWrap(handlerHandler)
	engine := newGinEngine(v)
	application := newApplication(sugaredLogger, engine)
	return application, nil
}

// wire.go:

var providerSet = wire.NewSet(
	ProviderSet, api.ProviderSet, handler.ProviderSet, user.ProviderSet,
)
