// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewApplication() (Application, error) {
	logger, err := newLogger()
	if err != nil {
		return Application{}, err
	}
	sugaredLogger := newSugaredLogger(logger)
	engine := newGinEngine()
	application := newApplication(sugaredLogger, engine)
	return application, nil
}

// wire.go:

var providerSet = wire.NewSet(
	newSugaredLogger,
	newApplication,
	newGinEngine,
	newLogger,
)
